using System;
using NServiceBus;

namespace PubSub__NSB_SignalR.SignalRSubscriber1
{
    // This code is generated by ServiceMatrix
    public class GeneratedWebInitialization : INeedInitialization
    {
        public void Init()
        {
        }
    }
}
